version: '3.8'

services:
  postgres-test:
    image: postgres:15
    container_name: test_ordelyx_db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "55432:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-test-data: